import {
  CircleDollarSign,
  Contact,
  CreditCard,
  LogOut,
  PanelLeftInactive,
  Receipt,
  Settings,
  User2,
  Utensils,
} from "lucide-react";
import { Inter } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <aside
          id="separator-sidebar"
          className="fixed top-0 left-0 z-40 w-64 h-screen transition-transform -translate-x-full sm:translate-x-0"
          aria-label="Sidebar"
        >
          <div className="h-full flex flex-col px-3 py-4 overflow-y-auto bg-gray-50">
            <ul className="space-y-2 font-medium">
              <li>
                <Link
                  href="/"
                  className="flex items-center p-2 text-gray-800 rounded-lg dark:text-white hover:bg-gray-100 group"
                >
                  <PanelLeftInactive className="text-gray-500 group-hover:text-gray-700" />
                  <span className="ml-3">Dashboard</span>
                </Link>
              </li>
              <li>
                <Link
                  href="#"
                  className="flex items-center p-2 text-gray-800 rounded-lg dark:text-white hover:bg-gray-100 group"
                >
                  <Utensils className="text-gray-500 group-hover:text-gray-700" />
                  <span className="flex-1 ml-3 whitespace-nowrap">Menu</span>
                  {/* <span className="inline-flex items-center justify-center px-2 ml-3 text-sm font-medium text-gray-800 bg-gray-200 rounded-full dark:bg-gray-700 dark:text-gray-300">
                  Menu Items
                </span> */}
                </Link>
              </li>
              <li>
                <Link
                  href="#"
                  className="flex items-center p-2 text-gray-800 rounded-lg dark:text-white hover:bg-gray-100 group"
                >
                  <Receipt className="text-gray-500 group-hover:text-gray-700" />
                  <span className="flex-1 ml-3 whitespace-nowrap">Orders</span>
                </Link>
              </li>
              <li>
                <Link
                  href="#"
                  className="flex items-center p-2 text-gray-800 rounded-lg dark:text-white hover:bg-gray-100 group"
                >
                  <CreditCard className="text-gray-500 group-hover:text-gray-700" />
                  <span className="flex-1 ml-3 whitespace-nowrap">Sale</span>
                </Link>
              </li>
              <li>
                <Link
                  href="#"
                  className="flex items-center p-2 text-gray-800 rounded-lg dark:text-white hover:bg-gray-100 group"
                >
                  <Contact className="text-gray-500 group-hover:text-gray-700" />
                  <span className="flex-1 ml-3 whitespace-nowrap">
                    Employees
                  </span>
                </Link>
              </li>
              <li>
                <Link
                  href="#"
                  className="flex items-center p-2 text-gray-800 rounded-lg dark:text-white hover:bg-gray-100 group"
                >
                  <User2 className="text-gray-500 group-hover:text-gray-700" />
                  <span className="flex-1 ml-3 whitespace-nowrap">
                    Customer Management
                  </span>
                </Link>
              </li>
              <li>
                <Link
                  href="#"
                  className="flex items-center p-2 text-gray-800 rounded-lg dark:text-white hover:bg-gray-100 group"
                >
                  <CircleDollarSign className="text-gray-500 group-hover:text-gray-700" />
                  <span className="flex-1 ml-3 whitespace-nowrap">
                    Promotions
                  </span>
                </Link>
              </li>
            </ul>
            <ul className="pt-4 mt-4 space-y-2 font-medium border-t border-gray-200 dark:border-gray-700">
              <li>
                <Link
                  href="/settings"
                  className="flex items-center p-2 text-gray-800 transition duration-75 rounded-lg hover:bg-gray-100 group dark:text-white group"
                >
                  <Settings className="text-gray-500 group-hover:text-gray-700" />
                  <span className="ml-4">Settings</span>
                </Link>
              </li>
              <li>
                <Link
                  href="#"
                  className="flex items-center p-2 text-gray-800 transition duration-75 rounded-lg hover:bg-gray-100 group dark:text-white group"
                >
                  <LogOut className="text-gray-500 group-hover:text-gray-700" />
                  <span className="ml-3">Log Out</span>
                </Link>
              </li>
            </ul>
            <p className="mt-auto font-medium text-gray-800">
              Welcome back, admin!
            </p>
          </div>
        </aside>

        <main className="pl-64 overflow-x-auto w-screen">{children}</main>
      </body>
    </html>
  );
}
