import { Toaster } from "@/components/ui/toaster";

import ProviderWrapper from "@/components/provider-wrapper";
import QueryWrapper from "@/components/query-wrapper";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <QueryWrapper>
          <ProviderWrapper>
            <main>{children}</main>
          </ProviderWrapper>
          <Toaster />
        </QueryWrapper>
      </body>
    </html>
  );
}
