"use client";

import useAuth from "@/utils/useAuth";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Admin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const { isLoading } = useAuth();
  if (isLoading) {
    return <div>Loading...</div>;
  }

  return <section className="bg-white">{children}</section>;
}
