export const metadata = {
  title: "Checkout",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <section className="bg-white"> {children}</section>;
}
